<?php

/**
 * @file
 * Module file for HRITServer collation views
 */

/**
 * @defgroup collationtools AustESE collation views
 * @ingroup austese
 * @{
 * AustESE collation views
 *
 */

/**
 * Implements hook_help().
 *
 */
function collationtools_help($path, $arg) {
  switch ($path) {
    case 'collationtools/apparatus':
      return t('AustESE collation views');

    case 'admin/help#collationtools':
      // Help text for the admin section, using the module name in the path.
      return t('AustESE collation views');
  }
}

/**
 * Implements hook_permission().
 *
 */
function collationtools_permission() {
  return array(
    'view collation tools' => array(
      'title' => t('View collation tools'),
      'description' => t('Allow users to view collation tools'),
    )
  );
}

/**
 * Implements hook_menu().
 *
 *
 * @see hook_menu()
 * @see menu_example
 */
function collationtools_menu() {
  // by default any path after this is split and provided as args to alignment_view
  $items['collationtools/apparatus'] = array(
    'title' => 'Apparatus Table Demo',
    'page callback' => 'collationtools_tableapparatus',
    'access arguments' => array('view collation tools'),
    'type' => MENU_CALLBACK
  );
  return $items;
}


function collationtools_tableapparatus($left=null, $right=null) {
  $extjs = 'ext-4.1.1a';
  //if (($library = libraries_detect($extjs)) && !empty($library['installed'])) {
  $modulePath = drupal_get_path('module', 'collationtools');
  drupal_add_css($modulePath . '/ui/app.css');
      drupal_add_js('/sites/all/libraries/ext-4.1.1a/ext-all.js');
  drupal_add_js($modulePath . '/ui/app.js');
  return theme('tableapparatus',array('left'=>$left, 'right'=>$right));
  //} else {
  //    return t('Please install ext-4.1.1a into /sites/all/libraries');
  //}

}
function collationtools_theme(){
 return array(
    'tableapparatus' => array(
       'template' => 'tableui',
       'variables' => array('left'=> null, 'right'=>null)
     )
 );
}

/**
 * @} End of "defgroup collationtools".
 */
