<?php

/**
 * @file
 * Module file for HRITServer collation views
 */

/**
 * @defgroup collationtools AustESE collation views
 * @ingroup austese
 * @{
 * AustESE collation views
 *
 */

/**
 * Implements hook_help().
 *
 */
function collationtools_help($path, $arg) {
  switch ($path) {
    case 'collationtools':
      return t('AustESE Collation Tools');
    case 'collationtools/apparatus':
      return t('AustESE collation views');
    case 'collationtools/compare':
      return t('AustESE collation compare view');
    case 'collationtools/slider':
      return t('Alternative slider');
    case 'admin/help#collationtools':
      // Help text for the admin section, using the module name in the path.
      return t('AustESE collation views');
  }
}

/**
 * Implements hook_permission().
 *
 */
function collationtools_permission() {
  return array(
    'view collation tools' => array(
      'title' => t('View collation tools'),
      'description' => t('Allow users to view collation tools'),
    )
  );
}

/**
 * Implements hook_menu().
 *
 *
 * @see hook_menu()
 * @see menu_example
 */
function collationtools_menu() {
  // by default any path after this is split and provided as args to alignment_view
  $items['collationtools'] = array(
    'title' => 'Collation Tools',
    'page callback' => 'collationtools_toc',
    'access arguments' => array('view collation tools'),
    'type' => MENU_CALLBACK
  );
  $items['collationtools/apparatus'] = array(
    'title' => 'Apparatus Table',
    'page callback' => 'collationtools_tableapparatus',
    'access arguments' => array('view collation tools'),
    'type' => MENU_CALLBACK
  );
  $items['collationtools/compare'] = array(
    'title' => 'Compare',
    'page callback' => 'collationtools_compare',
    'access arguments' => array('view collation tools'),
    'type' => MENU_CALLBACK
  );
  $items['collationtools/slider'] = array(
    'title' => 'Slider Demo',
    'page callback' => 'collationtools_tableapparatus2',
    'access arguments' => array('view collation tools'),
    'type' => MENU_CALLBACK
  );
  $items['collationtools/sendtomvd'] = array(
    'title' => 'Send to MVD',
    'page callback' => 'collationtools_sendtomvd',
    'access arguments' => array('view collation tools'),
    'type' => MENU_CALLBACK
  );
  return $items;
}
function collationtools_toc(){
  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = t(drupal_get_title()); 
  drupal_set_breadcrumb($breadcrumb);
  $list[] = l("Compare","collationtools/compare");
  $list[] = l("Table Apparatus","collationtools/apparatus");
  $render_array['collationtools_list'] = array(
    '#theme' => 'item_list',
    '#items' => $list
  );
  return $render_array;
}
function collationtools_compare($left=null, $right=null) {
  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('Collation Tools', 'collationtools');
  $breadcrumb[] = t(drupal_get_title()); 
  drupal_set_breadcrumb($breadcrumb);
  $modulePath = drupal_get_path('module', 'collationtools');
  drupal_add_css($modulePath . '/ui/app.css');
  drupal_add_js('/sites/all/libraries/ext-4.1.1a/ext-all.js');
  drupal_add_js($modulePath . '/ui/compareapp.js');
  return theme('extjsapp',array('left'=>$left, 'right'=>$right));
}
function collationtools_tableapparatus($left=null, $right=null) {
  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('Collation Tools', 'collationtools');
  $breadcrumb[] = t(drupal_get_title()); 
  drupal_set_breadcrumb($breadcrumb);
  $extjs = 'ext-4.1.1a';
  //if (($library = libraries_detect($extjs)) && !empty($library['installed'])) {
      $modulePath = drupal_get_path('module', 'collationtools');
      drupal_add_css($modulePath . '/ui/app.css');
      drupal_add_js('/sites/all/libraries/ext-4.1.1a/ext-all.js');
      drupal_add_js($modulePath . '/ui/app.js');
      return theme('extjsapp',array('left'=>$left, 'right'=>$right));
  //} else {
  //    return t('Please install ext-4.1.1a into /sites/all/libraries');
  //}

}
function collationtools_sendtomvd($ids=null){
    // FIXME: should not hardcode these values - should be in properties somewhere
    $hritimport = 'http://' . $_SERVER['HTTP_HOST'] . "/import/";
    // generate a unique document identifier for new MVD if docpath isn't specified
    $docpath = $_GET['docpath'];
    if ($docpath == null){
        $docpath = uniqid();
    }
    if ($ids==null){
        return t('Identifiers of resources to add to MVD not specified');
    }
    $docpath = urlencode($docpath);
    $resids = explode(";", $ids);
    
    $boundary = "-------------".uniqid();
    $data = "";

    foreach($resids as $resid) {
        if ($resid != ""){
            $resurl = 'http://' . $_SERVER['HTTP_HOST'] . "/" . drupal_get_path('module', 'repository') . "/api/resources/" . $resid;
            // load contents for resource
            $contents = file_get_contents($resurl);
            $data .= "--".$boundary."\r\n";
            $data .= "Content-Disposition: form-data; name=\"uploadedfile[]\"; filename=\"".$resid."\"\r\n";
            //$data .= "Content-Type: text/plain\r\n";
            $data .= "Content-Length: ".strlen($contents)."\r\n";
            $data .= "Content-Transfer-Encoding: binary\r\n\r\n";
            $data .= $contents."\r\n";
        }
    }
    $data .= "--".$boundary."\r\n";
    $data .= "Content-Disposition: form-data; name=\"DOC_ID\"\r\n\r\n". $docpath. "\r\n";
    $data .= "--". $boundary."--\n";
    
    $ch = curl_init();
    // post to HRIT server import
    curl_setopt($ch, CURLOPT_URL, trim($hritimport));
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-type: multipart/form-data; boundary=".$boundary));
    // get back status or response
    $response = curl_exec ( $ch );
    $err = curl_errno ( $ch );
     
    $header = curl_getinfo ( $ch );
    $httpCode = curl_getinfo ( $ch, CURLINFO_HTTP_CODE );
    
    $error = curl_error($ch);
    curl_close($ch);
    // TODO store MVD document id
    if ($err) {
        return t('Error: '. $err . " " . $error);
    } else {
        return t('<p>'.$response .
            '</p><p>If there were no errors indicated above, ' .
            'you may now view as a <a href="/collationtools/apparatus#' . $docpath .'">table apparatus</a> or <a href="/collationtools/compare#' . $docpath .'">side-by-side comparison</a></p>');
    }
    
}
function collationtools_tableapparatus2($left=null, $right=null) {
   return theme('tableapparatus2',array('left'=>$left, 'right'=>$right));
}
function collationtools_theme(){
 return array(
    'extjsapp' => array(
       'template' => 'tableui',
       'variables' => array('left'=> null, 'right'=>null)
     ),
     'tableapparatus2' => array(
       'template' => 'slider',
       'variables' => array('left'=> null, 'right'=>null)
     )
 );
}

/**
 * @} End of "defgroup collationtools".
 */
